# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6056c04144e5078511d9d32ce6c24c25154af91a64a718b42111fdb34f39219f9025a26ecec34d1daac353068019516f1e9a7419f76a50300bdedf7b5d77542b

test:
  secret_key_base: 5aa4a3de19260c5b8d06d1b283254e7b447bf2f1e76575252a7f5ba913099c0d5faab87e96f240ec1627bc5008115c97b8b6caa3113daad647312d64679a7337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
